sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JBNbGYUlspOLnCdNS4gGIzAA7lR+/L5EO5k7C992thTLLNR6rsNOPWqHXtDVrKQItj70iwPwUzb4eAXJLRbjHD0havZBeOMROvl3NGcgJnrqDtgL1cFClaNA0JA9XzcynPJ/DnfZlGjQXYr4cq8GL0T2KXOeNQ3BRhZyiMT3n/5BRzXeeZq0NHPTW82VPhXaoxVWMDX/5fECccmI0KBUt+K7Rhpe1ZUloHfRpxW3IT4xwQlroqCFcJAgnqtYkAUlPTvS/P/LxK5L8UPCO2flBWRdc4HWehLokgfYNgNI3xMgvkFkRy1IEDRDf/Y0CJYNXBMGvbLA8EuBZGAUAsxO2Sa4COWV36p9AOI/Y8J4r7wjKhtP4ha9aS/xLoKCi4ryqL4vayUN5F8n2hw/+yia5LRO/lsSLnzu2GOa2masSE4hq4FDb2OLfu7tNu1UVt+uSRhB1PImahT/6fOgSv7LWwYlrHpqY8mmo9iDjEiOjfN1COairSr1VkK7KYTX4TjK6cE/NSj5F13VQ69f5T+FSPdXWYBjJ3fkL4amvq19frkazqE6TxowomgY0nmPKxh9DPpcAiLe9BYgs/BgvtVULbZ0i7eIP9utwZGQXS/yHYRyJxCDrqZV/AZ85saImbtPCnWZDXpBO/+xq2LhFqMOrObOSkpxB5Sff03Mz6yuHUA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Arcadian-Adventures-with-the-Idle-Rich_4020
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy